//
// Created by layne on 19-4-27.
//

#ifndef AUDIO_EFFECT_ERROR_DEF_H_
#define AUDIO_EFFECT_ERROR_DEF_H_

#define AEERROR_NULL_POINT -1000
#define AEERROR_INVALID_PARAMETER -2000
#define AEERROR_NOMEM -5000
#define AEERROR_INVAL -5001
#define AEERROR_EXTERNAL -6000

#endif  // AUDIO_EFFECT_ERROR_DEF_H_
