#ifndef PITCH_MACRO_H_
#define PITCH_MACRO_H_

#define PITCH_FRAME_SHIFT 392
#define PITCH_BUFFER_SIZE (PITCH_FRAME_SHIFT * 3)
#define INV_PITCH_BUFFER_SIZE 8.503401e-4f
#define PITCH_SAMPLE_RATE 44100.0f
#define MAX_CAND_NUM 10
#define PITCH_CONFIDENCE_THRD 4
#define PITCH_VARIANCE_FACTOR 0.35f
#define LONG_TERM_PITCH_REFERENCE_LEN 500
#define PITCH_SEG_COUNT_THRD 8
#define PITCH_AVERAGE_UPDATE_THRD 50
#define IN_RANGE_LEN (4 * PITCH_FRAME_SHIFT)
#define LAST_JOINT_SIZE (PITCH_BUFFER_SIZE >> 1)
#define NOISE_PERIOD (0.004f * 44100.0f)

#define FREQUENCY_CEIL 600.0f
#define FREQUENCY_FLOOR 75.0f

#define FLOOR_NOISE_PERIOD 176
#define PI 3.1415926535f
#define MORPH_BUF_LEN (9 * PITCH_FRAME_SHIFT)

#endif  // PITCH_MACRO_H_
